name = "noxium-portfolio"
compatibility_date = "2024-12-12"

[env.production]
name = "noxium-portfolio"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[[env.production.routes]]
pattern = "*"
zone_name = "your-domain.com"